### ISSUE TITLE
FYI, small changes to Julia wildboottest() interface

### ISSUE THREAD

**Issue by droodman** [s3alfisc/fwildclusterboot#103]
I just posted version 0.9.7 of WildBootTests.jl. It includes a couple of changes to the optional arguments, which shouldn't affect fwildclusterboot very much:

1. The `NFE` argument is no longer accepted. This was a way to tell the program how many fixed-effect groups there are, and served only to save a little time.
2. It now accepts a Boolean argument `overwrite`, which communicates that it's OK to overwrite the supplied data matrices. This saves time and memory in some cases. Probably you can use this because I expect that in the transfer of data from R to Julia, the matrices are being _copied_, and it's fine to dirty the temporary Julia copies. This option helps less often than one might hope. If the data are clustered and issorted=false, then wildboottest() needs to sort the data by cluster, and it does so by storing the sorted data in new matrices anyway. (Sorting in place is not necessarily faster.) Then it never touches the user's data matrices after that, and the `overwrite` option doesn't matter. Another way to invoke the `overwrite` option is to call `wildboottest!` instead of `wildboottest`.
3. FWIW, I added waldtest() and scoretest() functions, which correspond to commands of the same name in the Stata package.

I've made a lot of speed improvements to the WRE in the last few months, so hopefully you'll see that in any benchmarks you run.

**Comment by s3alfisc** [comment]
Hi David - thanks for the update! I will have some free time over the Easter break and will take a closer look / try to accommodate all these changes then. I will let you know about any updates!

**Comment by s3alfisc** [comment]
It looks like CIs have changed slightly, I will have to update my unit tests, which failing under the newest version of WildBootTests.jl. [link to CI](https://github.com/s3alfisc/fwildclusterboot/actions/runs/4656697602/jobs/8240570717)
