### ISSUE TITLE
srr standards not parsed correctly

### ISSUE THREAD

**Issue by helske** [s3alfisc/fwildclusterboot#111]
The `srr_report()` for the package fails with somewhat cryptic error message `This is not an 'srr' package.` because in `srr_stats_standards.R` the necessary `NULL` values are commented out, e.g.
```
#' @srrstats {RE7.0} *Tests with noiseless, exact relationships between
#' predictor (independent) data.*
#' 
#' @noRd
# NULL
```
Tagging @meghapsimatrix who noticed this issue first. Also tagging @mpadge, I suggest that the error message could be bit more informative (e.g. "could not find any srr tags in package's Rd files" or something similar.

**Comment by s3alfisc** [comment]
Hi @helske, is this something that I can fix? Should I just un-comment the NULL value?

**Comment by mpadge** [comment]
@s3alfisc yep, indeed. Just replace `# NULL` with `NULL`

**Comment by s3alfisc** [comment]
Should be fixed =)

**Comment by helske** [comment]
You think you need to update the `srr` package from github or r-runiverse.

**Comment by s3alfisc** [comment]
Yes, updating the `srr` package does the job. =)
