### ISSUE TITLE
Cran Error in Suggests related to "lfe"

### ISSUE THREAD

**Issue by s3alfisc** [s3alfisc/fwildclusterboot#12]
"Please see the problems shown on
<https://cran.r-project.org/web/checks/check_results_fwildclusterboot.html>.

Please correct before 2021-08-08 to safely retain your package on CRAN.

Packages in Suggests should be used conditionally: see 'Writing R Extensions'.
This needs to be corrected even if the missing package(s) become available."
From "writing R extensions":

"1.1.3.1 Suggested packages

Note that someone wanting to run the examples/tests/vignettes may not have a suggested package available (and it may not even be possible to install it for that platform). The recommendation used to be to make their use conditional via if(require("pkgname")): this is OK if that conditioning is done in examples/tests/vignettes, although using if(requireNamespace("pkgname")) is preferred, if possible. "

**Comment by s3alfisc** [comment]
Added `if(requireNamespace("pkgname"))` statements for suggested packages in the vignettes, examples and tests. 

Note that unit tests will now only execute on CRAN if both `fixest` and `lfe` can be installed on the specific OS.

Currently, package installation fails on ubuntu-20.04 (devel) because installation of "lfe" fails (based on commit c84fffedf6d9bbf1a6c1ef9514717331251dac6d).

**Comment by MatthieuStigler** [comment]
lfe 2.8-7 was just accepted on CRAN, this should fix the issue!?

**Comment by s3alfisc** [comment]
Hi Mathieu, thanks for letting me know! This indeed fixes this issue :) 
All bugs mentioned above are now adressed with version 0.3.6 and commit bf3d28929c0978b38f3f6b14b7945b93111e6177 & `fwildclusterboot` 0.3.6 is on CRAN!
