### ISSUE TITLE
Error in terms.formula(tmp, simplify = TRUE) : invalid model formula

### ISSUE THREAD

**Issue by ccmullally** [s3alfisc/fwildclusterboot#26]
I'm receiving the above error when trying to run boottest using a feols model. I don't have same issue with lm. I'm probably doing something wrong, but just in case this is a bug, I wanted to let you know. 
```

library(dplyr)
library(fwildclusterboot)
library(fixest)
# 
data(mtcars)
feols_fit <- feols(disp ~  am + hp, weights = ~qsec, cluster = ~cyl, data = mtcars)

boot_feols <- boottest(feols_fit, clustid = "cyl", param = "am", B = 499)

lm_fit <- lm(disp ~  am + hp, mtcars, weights = qsec)

boot_lm <- boottest(lm_fit, clustid = "cyl", param = "am", B = 499)
```

**Comment by s3alfisc** [comment]
Hi, thanks - `boottest()` currently only works if the weights argument is passed to `lm()` and `feols()` as a vector. I was not aware of this (fixest has a lot of different options to specify models, which makes my life rather complicated), so thanks for letting me know about it! I'll try to fix this over the next days. 

Until then, a workaround for you is to run

```
library(dplyr)
library(fwildclusterboot)
library(fixest)

# 
data(mtcars)

feols_fit <- feols(disp ~ am + hp, weights = mtcars$qsec, cluster = "cyl", data = mtcars)
boot_feols <- boottest(feols_fit, clustid = "cyl", param = "am", B = 499, seed = 986)

lm_fit <- lm(disp ~  am + hp, mtcars, weights = qsec)
boot_lm <- boottest(lm_fit, clustid = "cyl", param = "am", B = 499, seed = 986)

generics::tidy(boot_feols)
generics::tidy(boot_lm)
# > generics::tidy(boot_feols)
# term  estimate statistic p.value  conf.low conf.high
# 1 1*am = 0 -100.2779  -2.69509       0 -166.8028 -48.54865
# > generics::tidy(boot_lm)
# term  estimate statistic p.value  conf.low conf.high
# 1 1*am = 0 -100.2779  -2.69509       0 -166.8028 -48.54865
```

**Comment by s3alfisc** [comment]
Btw as you are new to R and use WLS - one difference between R and Stata is that R does not differentiate between frequency and sampling/probability weights. In R's `lm()` function, it is my understanding that weights are always treated as `sampling/probability` weights. This does not matter for point estimation, but for inference via small sample corrections - with frequency weights, the number of rows of the data M no longer corresponds to the number of observations N, and in consequence, R implements an incorrect small sample adjustment m = (M-k) / (M-1). This does not matter for wild bootstrap inference, as the p-value is calculated as mean(abs(m x t_stat) <= abs(m x t_boot)) - both t_stat and t_boot are multiplied with the same factor. I try to explain this in more detail [here](https://github.com/lrberge/fixest/issues/251).

**Comment by ccmullally** [comment]
Very interesting, thanks. I will add this to my problem set so the students know.

**Comment by ccmullally** [comment]
Fantastic, thanks.
