### ISSUE TITLE
New error message running boottest.felm

### ISSUE THREAD

**Issue by chayek** [s3alfisc/fwildclusterboot#50]
I was running boottest on an felm object with no problem in my script in the past. The line of code is:  

          boottest(reg_basic,  clustid = SEclusters, param=event_basic_BS, seed=27,  B=9999, fe=FEs, conf_int = TRUE, sign_level=0.05)

I had to reinstall R and all my packages after a computer issue and now that same code no longer works.  I'm thinking that it might be the result of either an updated version of R or an updated supporting package (perhaps dplyr?).  I get the following error, which begins with the regression equation from my felm object:

         Error in Year_cont + Year_cont:post1 + Year_cont:post2 | PWSID : 
            operations are possible only for numeric, logical or complex types
        Error in as.data.frame.default(data) : 
            cannot coerce class ‘"try-error"’ to a data.frame

It comes with a warning message about dplyr:  

         `funs()` was deprecated in dplyr 0.8.0.
         Please use a list of either functions or lambdas.

Any assistance is appreciated.

**Comment by s3alfisc** [comment]
Hi @chayek, 

Thanks for reaching out! A few quick comments from my side: 

1. `fwildclusterboot` does not depend on `dplyr` (not even indirectly through a dependency, only through suggests), so I would rule that out as a source of the error. 
2. Likely, this bug occurs due to some changes in pre-processing introduced in `fwildclusterboot` 0.9. If you estimate your model via `fixest::feols()`, does the same error occur? 
3. Can you provide me with a fully reproducible example? Could you potentially share your data and the function call with me? If you don't want to do so publicly, you could also send me the data by email (if that is an option for you). 
4. If you can't / don't want to share your data, can you run `boottest()` line by line until you arrive at the [`get_cluster()`](https://github.com/s3alfisc/fwildclusterboot/blob/master/R/preprocess2.R#L532) function? Is it `get_cluster()` that throws an error?

**Comment by chayek** [comment]
Thanks for the quick reply!! Unfortunately, I can not share the data.  I appreciate the link to the source code- I am not very familiar with how things are laid out for R packages on github.

get_cluster() is indeed where the error gets thrown, and in the first step:

    clustid_list <- get_cluster(
      object = object,
      clustid_char = clustid,
      N = N,
      bootcluster = bootcluster, 
      call_env = call_env
    )

**Comment by chayek** [comment]
oops, I meant to paste this code:

cluster_tmp <-
    try(
      if("Formula" %in% loadedNamespaces()) { ## FIXME to suppress potential warnings due to | in Formula
        suppressWarnings(expand.model.frame(
          model = object,
          extras = clustid_fml, 
          na.expand = FALSE, 
          envir = call_env
        )
      )
      } else {
        expand.model.frame(
          object, 
          clustid_fml,
          na.expand = FALSE, 
          envir = call_env
        )
      }
    )

Error in Year_cont + Year_cont:post1 + Year_cont:post2 | PWSID : 
  operations are possible only for numeric, logical or complex types

**Comment by s3alfisc** [comment]
Excellent! Can you provide me with the full call to _felm()_, i.e. how you specify your model including the model formula, and further the data type of all data columns employed (e.g. the output of sapply(data, class))?

**Comment by s3alfisc** [comment]
Are you interacting fixed effects in the formula? If yes, that might be the source of the error. I am aware that fixed effect interactions via _^_ are not supported for _fixest_ models, and it might be the same for interactions via _:_

Can you try to create your fixed effect with _paste(var1,var2)_ and run the model without specifying the interaction via _:_ in the formula?

**Comment by chayek** [comment]
sure!

I generate the regression equations via a for loop set like this:
growth_gen <- "Year_cont"
growth_diffs <- c("post1","post2")
FEs <- c("PWSID")
SEclusters <- c("Utility_state")
IVs <- 0
charges <- c("real_0", "real_500", "real_1000", "real_1500", "real_3000")
outcome_vars <- paste("log(", charges ,")", sep="") 

the for loop sets log_charge = outcome_vars[i]
reg_basic <- felm(as.formula(paste(log_charge, "~", growth_gen, "+",                         #time
                                     paste(growth_gen, growth_diffs, sep=":",collapse= "+"),   #period differences interacted with time
                                     paste("|", paste(FEs, IVs, SEclusters, sep= " | ")))), 
                    data=event_reg_data, keepX=TRUE)

For charge of "real_1000", this is the equivalent of running:
reg_basic <- felm(log(real_1000) ~ Year_cont + Year_cont:post1 + Year_cont:post2 | 
                       PWSID | 0 | Utility_state, data=event_reg_data, keepX=TRUE)

The error happens regardless of which generation method I use.

Class and summary of the data being used:
> sapply(event_reg_data[c("real_1000", "Year_cont", "post1", "post2", "PWSID", "Utility_state")], class)
    real_1000     Year_cont         post1         post2         PWSID Utility_state 
    "numeric"     "numeric"     "numeric"     "numeric"   "character"   "character"

> summary(event_reg_data[,c("real_1000", "Year_cont", "post1", "post2", "PWSID", "Utility_state")])
   real_1000        Year_cont         post1            post2          PWSID           Utility_state     
 Min.   :  6.81   Min.   :-8.00   Min.   :0.0000   Min.   :0.000   Length:2010        Length:2010       
 1st Qu.: 22.03   1st Qu.:-2.00   1st Qu.:0.0000   1st Qu.:0.000   Class :character   Class :character  
 Median : 28.82   Median : 2.00   Median :0.0000   Median :0.000   Mode  :character   Mode  :character  
 Mean   : 31.29   Mean   : 1.49   Mean   :0.2478   Mean   :0.301                                        
 3rd Qu.: 37.48   3rd Qu.: 6.00   3rd Qu.:0.0000   3rd Qu.:1.000                                        
 Max.   :123.09   Max.   :10.00   Max.   :1.0000   Max.   :1.000      

my looped bootstrap code is:
event_basic_BS <- c("Year_cont", "Year_cont:post1", "Year_cont:post2")
boottest(reg_basic,  clustid = SEclusters[1], param=event_basic_BS , seed=27, 
         B=9999, fe=FEs[1], conf_int = TRUE, sign_level=0.05)

which is the equivalent of 
boottest(reg_basic,  clustid = "Utility_state", param=c("Year_cont", "Year_cont:post1", "Year_cont:post2"), seed=27, 
         B=9999, fe="PWSID", conf_int = TRUE, sign_level=0.05)

Again, both give errors,

**Comment by chayek** [comment]
I don't interact fixed effects, so I'm not sure your last suggestion applies. Let me know if I've made a mistake there.

**Comment by s3alfisc** [comment]
Note that this error also occurs with `sandwich::vcovCL()`, from which I have copied the way the cluster-preprocessing in `fwildclusterboot` works (via `get_cluster()`): 

```
library(sandwich)
sandwich::vcovCL(reg_basic_lfe, 
                 cluster = ~Utility_state)
# Error in Year_cont + Year_cont:post1 + Year_cont:post2 | PWSID : 
#  operations are possible only for numeric, logical or complex types
```
cc @zeileis (for your information).

**Comment by s3alfisc** [comment]
Hi @chayek, 

A hot fix for you is to convert all variables you use as fixed effects and cluster variables to `factors`. The error occurs due to `expand.model.frame()`, a base method which does not work with objects of type `felm` and `fixest` if there are non-numeric or non-factor variables specified in the model formulas. 

I suppose that I need to convert all of these to factors internally to avoid such behavior - as a matter of fact, this is already happening for all fixed effects, but in a later part of the code. Hopefully, I'll be able to ship these changes to CRAN by the end of the week. 

By comparing to the t-stat computed via `fixest`, you can verify that `boottest()` works as intended - it's internally computed t-stat should exactly match the t-stat computed by `fixest::feols()`. (I compare with fixest as it allows for more control over small sample corrections. Also, note that `fixest` supports a very flexible [multiple estimation syntax](https://cran.r-project.org/web/packages/fixest/vignettes/multiple_estimations.html) that works well with `fwildclusterboot` - since version 0.9). 

```
library(lfe)
library(fixest)
library(fwildclusterboot)

N <- 1000

real_1000 <- runif(N, 1, 100)
Year_cont <- sample(1:10, N, replace = TRUE)
post1 <- sample(0:1, N, replace = TRUE)
post2 <- sample(0:1, N, replace = TRUE)
PWSID <- sample(LETTERS, N, TRUE)
Utility_state <- as.character(sample(1:10, N, TRUE))
SEclusters <- as.character(sample(1:10, N, TRUE))

event_reg_data <- 
  data.frame(real_1000 = real_1000, 
             Year_cont = Year_cont, 
             post1 = post1, 
             post2 = post2, 
             PWSID = PWSID, 
             Utility_state = Utility_state, 
             SEclusters = SEclusters)

#event_reg_data$PWSID <- factor(event_reg_data$PWSID)
event_reg_data$Utility_state <- factor(event_reg_data$Utility_state)
event_reg_data$PWSID <- factor(event_reg_data$PWSID)

object <- felm(
    real_1000 ~ Year_cont + Year_cont:post1 + Year_cont:post2 | 
    PWSID | 
    0 | 
    Utility_state,
  data=event_reg_data, 
  keepX=TRUE)

res <- 
fwildclusterboot::boottest(
  object = object, 
  param = names(coef(object))[1], 
  clustid = ~ Utility_state, 
  B = 9999, 
  fe = ~PWSID, 
  ssc = boot_ssc(adj = FALSE, 
                 cluster.adj = FALSE)
)

object <- feols(
  real_1000 ~ Year_cont + Year_cont:post1 + Year_cont:post2 | 
    PWSID, 
    cluster = ~ Utility_state,
  data=event_reg_data
)

res$t_stat
# [1] -0.8751922
tstat(object, 
      ssc = ssc(adj = FALSE, 
                cluster.adj = FALSE)
)
#      Year_cont Year_cont:post1 Year_cont:post2 
 #   -0.87519222     -0.08893067      0.29618529 
```

**Comment by s3alfisc** [comment]
I added a check for this usecase, see the commit above. In short, I try to provide a clearer error message that asks users to convert all character variables into factors prior to calling `feols()` or `felm()`. I am currently running unit tests - if they pass, version `0.9.1` should be downloadable from `r-universe` within the hour, and I will also submit to CRAN.

**Comment by chayek** [comment]
Thanks so much Alex! For the hot fix and for finding a more permanent
solution so quickly :-)

Carolyn

**Comment by s3alfisc** [comment]
Hi, as one core dependency, 'gtools', is currently orphaned on cran but - as it appears - transitioning to a new maintainer, I will wait a couple more days before submitting to Cran. Until then, 'fwildclusterboot' 0.9.1 can be downloaded from r-universe. I'll keep this thread open until the new version is back on Cran!
