### ISSUE TITLE
Consider python port?

### ISSUE THREAD

**Issue by amichuda** [s3alfisc/fwildclusterboot#61]
Hi!

I'm currently doing some analysis, and I need the wild cluster bootstrap, but it's not really available in Python. Do you know of a python port somewhere? Or if not, do you know the R code I should look at that has the "meat" so to speak? What would be my quickest path to a quick and dirty implementation?

**Comment by s3alfisc** [comment]
Hi - there is a python implementation of the package called [clusterbootstraps](https://pypi.org/project/clusterbootstraps/), but I have never used it, so cannot attest of its quality. [WildBootTests.jl](https://github.com/droodman/WildBootTests.jl) has an example of how to call it from Python (via PyJulia) - that might be another convenient solution.

 I was thinking of working towards a PR for `statsmodels` at some point in the future, most likely implementing the algorithm following [MacKinnon](https://www.econstor.eu/bitstream/10419/247206/1/qed-wp-1465.pdf), which is implemented in most basic form in the [boot_algo3](https://github.com/s3alfisc/fwildclusterboot/blob/master/R/boot_algo3.R) function (in case you wanted to get started with it =) ). [boot_algo2](https://github.com/s3alfisc/fwildclusterboot/blob/master/R/boot_algo2.R) instead follows the algorithm as laid out in the "fast and wild" paper. The "traditional brute force" WCB algo is implemented in [wildboottest.cpp](https://github.com/s3alfisc/fwildclusterboot/blob/master/src/wildboottest.cpp#L204) in probably fairly poor cpp :)

**Comment by amichuda** [comment]
I might just take you up on that! Let's see if I can port it over to python. 

My current problem involves panel data and multiple way fixed effects, will `boot_algo3` work in that context?

I use `linearmodels` for fixed effects regression, so it would be nice to write up a package that's agnostic to the input regression model and then make PRs in both?

**Comment by s3alfisc** [comment]
Hi @amichuda - I will have time to work on an initial python implementation of the MacKinnon algorithm at the beginning of October, when I'll have two weeks off and plans to push my open source projects a little. Would that timeline fit you, or is there more urgency in your project? And yes, fixed effects should eventually be supported, and I agree to aim to make the algo work with both `linearmodels` and `statsmodels`. =)

**Comment by amichuda** [comment]
Yes, that timeline might work, but I'm also game to help in the coding. Would this be essentially a port of `boot_algo3`?

If you're game to work together, do you want to make a new package repo or just add it into this one?

Let me know!

**Comment by s3alfisc** [comment]
Very cool! I would suggest to start a new repo and to develop pybootest/pywildclzsterboot over there. Please go ahead with creating it! 

I will send you my "debugging scripts" for fwildclusterboot later today - they should help you to compute all the input variables of the 'boot_algo' functions. Via rpy2 or reticulate, it should be easy to compute all of these in R and pass them to your python session, which (I believe) should help you to get started with the implementation.

You could either try to develop the first part of a method for linearmodels that would compute all these input objects, or you could use them to start working on the actual bootstrap algorithms (or even both!😀). I believe the first would take me quite some time, while writing the algo should be fairly quick for me. 

I suggest to start with boot_algo3 for the following reasons: 
- it explicitly outputs bootstrapped covariances matrices (which the fast and wild algorithm does not do)
- it's fairly easy to add all new wild cluster bootstrap versions from MacKinnon, Nielsen and Webb, who seem to perform really, really well
- it's fairly fast (though slower than boot_algo2) 

I have a few other design considerations, but I might share them with you via email or the new repo. Looking forward to collaborate on this! 

Best, Alex

**Comment by s3alfisc** [comment]
Python version in development [here](https://github.com/s3alfisc/wildboottest).
