### ISSUE TITLE
Non-clustered Wild Bootstrap

### ISSUE THREAD

**Issue by LootInvest** [s3alfisc/fwildclusterboot#7]
Dear Alexander Fischer. 

Thank you for the package. Currently trying to perform a non-clustered wild bootstrap. But R keeps demanding clusterid. 

Could you elaborate on whether clusterid can be removed, and how this is done? Current code is: 

marketbw_boot <- boottest(mkt_bw, B = 1000, clustid =0, param = "lag(BW_orth, k = 1)")

If I remove clustid, it cannot run, neither can above code.

**Comment by s3alfisc** [comment]
Hi, 

`clustid` is a required argument, so it's good that the package throws an error when you're not supplying an argument. :) 

If you want to run boottest() without clustering, you need to set clustid = "id_var", where "id_var" is your id variable. Note that if your sample size is large, boottest() will probably not be very fast, as the underlying algorithm is optimized for the case of few clusters and require a lot of memory (see the benchmarks on the readme page).
