### ISSUE TITLE
Individual event study confidence intervals

### ISSUE THREAD

**Issue by lparisi94** [s3alfisc/fwildclusterboot#78]
Hello Alex,

First of all thanks for helping develop all these cool R packages! 

I have just one small question, is it possible to use this package to wild cluster my standard errors in an event study? 

For example, I'm using the following code:

pre_twfe = feols(log_rate ~ i(stimetotreatment, treatment_group, ref = -1) 
                 | scode + year, weights = ~population, data = guns)

I would like to get the correct confidence intervals for each estimate individually. Is this possible? 

Any help would be highly appreciated! Thank you.

Best,

Luka

**Comment by s3alfisc** [comment]
Hi Luka, 

Thanks for the nice words :) I'm super sorry I did not respond earlier, somehow github did not notify my about your question (at least the app didn't, which I checked over the weekend). 

In general yes, this should be possible. You would have to do the following: 

- get all the coefficient names of interest via e.g. `coef_names <- names(coef(pre_twfe))`
- loop over all coefficients along the following lines (in pseudo code): 
```
multiple_bootstraps <- lapply(coef_name, function(x){
     boottest(pre_twfe, param = x, ...)
})
```
This unfortunately will not run 'straight out of the box' with some nice fixest functionality (e.g. etable) - I might try to come up with a nice workaround for that :) 

Note that I have recently added support for fixest's sunab() estimator, you can find the documentation [here](https://s3alfisc.github.io/fwildclusterboot/reference/boot_aggregate.html).

I hope this helps! Maybe I should add a dedicated vignette that runs through fwildclusterboot's DiD support? Do you think that would be helpful?

Best, Alex

**Comment by s3alfisc** [comment]
Unfortunately I don't have an ad hoc solution ad hand - you might have to code it up yourself, e.g. with [ggplot2::geom_errorbar()](https://ggplot2.tidyverse.org/reference/geom_linerange.html) for the confidence intervals. I'll think about this a bit. Maybe you can take some inspiration from the `plot_event_study()` function from [did2s](https://github.com/kylebutts/did2s/blob/cc42dcccb844849dc7da1ddd84d93b67062c9879/R/event_study.R#L314)? For getting confidence intervals out of an object of type boottest, you can simply use the `confint()` extractor method.

**Comment by lparisi94** [comment]
Thank you for all of your good suggestions and help. I will try to implement this and if I have any additional problems I will let you know.

Thanks again!

L.
