### ISSUE TITLE
arm64 Architecture Incompatibility

### ISSUE THREAD

**Issue by jcha1997** [s3alfisc/fwildclusterboot#83]
Hello again, 
I'm currently operating off a 2022 Macbook Pro, which runs off of an arm64 architecture. While the CRAN download supported this new architecture, the current devtools/github/r-universe ports do not, which is leading to compilation errors. Most of the previous issue errors seems to be a result of this issue as well. Currently, I believe the package installation relies on an x86 architecture, but I could be wrong. Thought I would open up an issue! 

Jeremiah

**Comment by s3alfisc** [comment]
Yes, this appears to still be [an open issue](https://github.com/r-universe-org/help/issues/97) within the r-universe ecosystem. Thanks for letting me know! I still have not heard back from CRAN (I re-submitted around two weeks ago) & hope that this will change rather soon =) Have you managed to install the package by downloading the github repo and installing it locally?

**Comment by s3alfisc** [comment]
One last thing to try is to download the tar.gz from the [CRAN archive ](https://cran.r-project.org/src/contrib/Archive/fwildclusterboot/)and try to install locally?

**Comment by jcha1997** [comment]
Unfortunately, I tried that as well

**Comment by s3alfisc** [comment]
`[fwildclusterboot](https://cran.r-project.org/web/packages/fwildclusterboot/index.html)` is back on CRAN! I suppose you will be able to download the binaries within the next days 😄
